-- MySQL Script generated by MySQL Workbench
-- Tue Jun 21 09:48:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inspiraction_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inspiraction_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inspiraction_db` DEFAULT CHARACTER SET utf8 ;
USE `inspiraction_db` ;

-- -----------------------------------------------------
-- Table `inspiraction_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`user` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(150) NOT NULL,
  `lastame` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(3000) NOT NULL,
  `birthday_date` DATETIME NULL,
  `role` VARCHAR(3000) NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `inspiraction_db`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`author` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(150) NOT NULL,
  `lastname` VARCHAR(150) NOT NULL,
  `speciality` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `inspiraction_db`.`masterclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`masterclass` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `source` VARCHAR(1000) NOT NULL,
  `description` VARCHAR(3000) NOT NULL,
  `author_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `author_Id`),
  INDEX `fk_masterclass_author1_idx` (`author_Id` ASC) VISIBLE,
  CONSTRAINT `fk_masterclass_author1`
    FOREIGN KEY (`author_Id`)
    REFERENCES `inspiraction_db`.`author` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `inspiraction_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`category` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `inspiraction_db`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`keyword` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `inspiraction_db`.`masterclass_has_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`masterclass_has_category` (
  `masterclass_Id` INT NOT NULL,
  `category_Id` INT NOT NULL,
  PRIMARY KEY (`masterclass_Id`, `category_Id`),
  INDEX `fk_masterclass_has_category_category1_idx` (`category_Id` ASC) VISIBLE,
  INDEX `fk_masterclass_has_category_masterclass_idx` (`masterclass_Id` ASC) VISIBLE,
  CONSTRAINT `fk_masterclass_has_category_masterclass`
    FOREIGN KEY (`masterclass_Id`)
    REFERENCES `inspiraction_db`.`masterclass` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_masterclass_has_category_category1`
    FOREIGN KEY (`category_Id`)
    REFERENCES `inspiraction_db`.`category` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `inspiraction_db`.`masterclass_has_keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`masterclass_has_keyword` (
  `masterclass_Id` INT NOT NULL,
  `keyword_Id` INT NOT NULL,
  PRIMARY KEY (`masterclass_Id`, `keyword_Id`),
  INDEX `fk_masterclass_has_keyword_keyword1_idx` (`keyword_Id` ASC) VISIBLE,
  INDEX `fk_masterclass_has_keyword_masterclass1_idx` (`masterclass_Id` ASC) VISIBLE,
  CONSTRAINT `fk_masterclass_has_keyword_masterclass1`
    FOREIGN KEY (`masterclass_Id`)
    REFERENCES `inspiraction_db`.`masterclass` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_masterclass_has_keyword_keyword1`
    FOREIGN KEY (`keyword_Id`)
    REFERENCES `inspiraction_db`.`keyword` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `inspiraction_db`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`favorite` (
  `user_Id` INT NOT NULL,
  `masterclass_Id` INT NOT NULL,
  PRIMARY KEY (`user_Id`, `masterclass_Id`),
  INDEX `fk_user_has_masterclass_masterclass1_idx` (`masterclass_Id` ASC) VISIBLE,
  INDEX `fk_user_has_masterclass_user1_idx` (`user_Id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_masterclass_user10`
    FOREIGN KEY (`user_Id`)
    REFERENCES `inspiraction_db`.`user` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_masterclass_masterclass10`
    FOREIGN KEY (`masterclass_Id`)
    REFERENCES `inspiraction_db`.`masterclass` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `inspiraction_db`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inspiraction_db`.`photo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `source` VARCHAR(255) NOT NULL,
  `author_Id` INT NOT NULL,
  PRIMARY KEY (`Id`, `author_Id`),
  INDEX `fk_photo_author1_idx` (`author_Id` ASC) VISIBLE,
  CONSTRAINT `fk_photo_author1`
    FOREIGN KEY (`author_Id`)
    REFERENCES `inspiraction_db`.`author` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
